name: Test

on:
  workflow_call:
    inputs:
      python-versions:
        required: true
        type: string
      timeout-minutes:
        type: number
        required: false
        default: 5

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout-minutes }}
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          pip install uv
          uv pip install -r requirements-dev.txt --system

      - name: Run Python Tests
        run: |
          pytest . -vv
