name: Check for version in README.md

on:
  workflow_call:
    inputs:
      prefix:
        required: false
        type: string

jobs:
  check-readme:
    uses: ./.github/workflows/version-check.yaml
    with:
      filename: README.md
      prefix: ${{ inputs.prefix }}
