name: Lint and Format Rust Files with Cargo and Clippy

on:
  workflow_call:
    inputs:
      rust-version:
        required: true
        type: string
      hack-flags:
        type: string
        required: false
        default: ""

jobs:
  cargo-lint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          lfs: true
          submodules: recursive

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: ${{ inputs.rust-version }}

      - uses: taiki-e/install-action@cargo-hack

      - name: Format with Cargo
        run: |
          cargo fmt --check

      - name: Check with Cargo
        run: |
          cargo hack check --workspace --all-targets ${{ inputs.hack-flags }}

      - name: Lint with Clippy
        run: |
          cargo hack clippy --workspace --all-targets ${{ inputs.hack-flags }}
